### ISSUE TITLE
Assignment 2: Adivinhe a palavra

### ISSUE THREAD

**Issue by gabiduarte** [bbiamichelle/estudos#5]
Very nice Bia!! 👍 

There's two small things that can be improved:

## [Are you using this import?](https://github.com/bbiamichelle/estudos/blob/eff33078812499002616f30296ee2139f02c7773/Forca.java#L1)
I ran  the program without this statement and everything is working. Do you need it to make your program run?

## [Retry if you got it wrong](https://github.com/bbiamichelle/estudos/blob/eff33078812499002616f30296ee2139f02c7773/Forca.java#L21)

If you got the word wrong you can't do it again, even though the message says to try again. In that case maybe you can try to wrap the logic to keep asking for the word until you get it correct or have a word that will end the process (like if you type "sair").

**Comment by gabiduarte** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assignment 2:](https://trello.com/c/UsHf37VG/7-assignment-2)

**Comment by gabiduarte** [comment]
@bbiamichelle: Regarding the "Retry if you got it wrong" section, I need you to wrap the logic around the Scanner asking for the correct input or a word for you to quit. 

The only change you did was ask the person to think before trying it again. That's not working your logic.
https://github.com/bbiamichelle/Exercicios/blob/ae9ba9a29c10df0f33255793b90d5f8abb7f4d70/forca1/src/main/java/com/thoughtworks/App.java#L18

**Comment by bbiamichelle** [comment]
Gabi, look this exercise: https://github.com/bbiamichelle/Exercicios/blob/master/forca1/src/main/java/com/thoughtworks/App.java

**Comment by gabiduarte** [comment]
Nice! 🥇 I'm closing this issue then
